package com.oogzy.rpg.dnd.character.skill;

public enum SkillKey
{
	ACROBATICS, ARCANA, ATHLETICS, BLUFF, DIPLOMACY, DUNGEONEERING, ENDURANCE, HEAL, HISTORY, INSIGHT, INTIMIDATE, NATURE, PERCEPTION, RELIGION, STEALTH, STREETWISE, THIEVERY;
}